// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2mYTDO9l-a6BS8fnWgjFKsds4Wbqgk0s',
    appId: '1:535723044713:web:cdd8a413bc5e9277c217f8',
    messagingSenderId: '535723044713',
    projectId: 'academia-app-4d3a5',
    authDomain: 'academia-app-4d3a5.firebaseapp.com',
    storageBucket: 'academia-app-4d3a5.firebasestorage.app',
    measurementId: 'G-9DPPN38S27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnuLNgHsjVEqAWnLSUlucqrA5RCTNmCLA',
    appId: '1:535723044713:android:328d5dae63de36c0c217f8',
    messagingSenderId: '535723044713',
    projectId: 'academia-app-4d3a5',
    storageBucket: 'academia-app-4d3a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQeqNs-H9T8RcQCXR2fBv-qoxVSZSBaOQ',
    appId: '1:535723044713:ios:3e33171a6bd65a5dc217f8',
    messagingSenderId: '535723044713',
    projectId: 'academia-app-4d3a5',
    storageBucket: 'academia-app-4d3a5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQeqNs-H9T8RcQCXR2fBv-qoxVSZSBaOQ',
    appId: '1:535723044713:ios:3e33171a6bd65a5dc217f8',
    messagingSenderId: '535723044713',
    projectId: 'academia-app-4d3a5',
    storageBucket: 'academia-app-4d3a5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2mYTDO9l-a6BS8fnWgjFKsds4Wbqgk0s',
    appId: '1:535723044713:web:98e94d0edd57ae76c217f8',
    messagingSenderId: '535723044713',
    projectId: 'academia-app-4d3a5',
    authDomain: 'academia-app-4d3a5.firebaseapp.com',
    storageBucket: 'academia-app-4d3a5.firebasestorage.app',
    measurementId: 'G-8V9HP24M3P',
  );
}
